### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by jtpio** [jtpio/retrolab#118]
To:

- remove confusion around whether `jupyterlab-classic` is (or should be) an official frontend
- not fragment the Jupyter frontend ecosystem with yet another frontend and avoid confusing users 

However we should continue to publish the application to PyPI, npm and conda so it can be easily used.

### TODO

- [x] Rename the code: #121
- [x] Rename the GitHub repo
- [x] Update screenshots and screencasts
- [x] Release `0.2.0rc` to PyPI: https://pypi.org/project/retrolab/0.2.0rc0/
- [x] Publish the `npm` packages: https://www.npmjs.com/package/@retrolab/application
- [x] Update secret tokens on GitHub to fix the automated releases 
- [x] Rename App to RetroLab: https://github.com/jtpio/retrolab/issues/110
- [x] Cut `0.2.0rc1`
- [x] Automate the `0.2.0` release: https://pypi.org/project/retrolab/0.2.0/
- [x] Add instructions to update in the GitHub release notes: https://github.com/jtpio/retrolab/releases/tag/0.2.0
- [x] Create the new conda feedstock: https://anaconda.org/conda-forge/retrolab
